import type { MetricDefinition } from '../types.js';

export const metricCatalog: MetricDefinition[] = [
  {
    metric: 'Total Users',
    purpose: 'Count of user profiles in the product.',
    sourceTable: 'profiles',
    sourceColumn: 'id',
    relationships: 'profiles is the canonical user record for product-level counts; company relationships remain subject to profile.company_id.',
    calculation: 'COUNT(DISTINCT profiles.id)',
    timeWindow: 'Since inception',
    userAttribution: 'profile.id',
    companyAttribution: 'profiles.company_id',
    dataLimitations: 'This measures record count, not necessarily successful authentication or active usage.',
    reliability: 'medium',
    available: true,
  },
  {
    metric: 'New Users',
    purpose: 'User accounts created during a time window.',
    sourceTable: 'profiles',
    sourceColumn: 'created_at',
    relationships: 'profiles.created_at is used for account creation counts.',
    calculation: 'COUNT(*) WHERE created_at in time window',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'profile.id',
    companyAttribution: 'profiles.company_id',
    dataLimitations: 'Creation date is not equivalent to first login.',
    reliability: 'medium',
    available: true,
  },
  {
    metric: 'Recently Updated Profiles',
    purpose: 'Proxy for recent profile updates to approximate activity when no true product event feed exists.',
    sourceTable: 'profiles',
    sourceColumn: 'updated_at',
    relationships: 'Profiles are filtered by updated_at within the requested time window.',
    calculation: 'COUNT(*) WHERE updated_at >= time window start',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'profile.id',
    companyAttribution: 'profiles.company_id',
    dataLimitations: 'Not a trustworthy login or product event metric. This is explicitly labeled as a recency proxy.',
    reliability: 'low',
    available: true,
  },
  {
    metric: 'Never Logged In',
    purpose: 'Users with no successful sign-in event on the auth record.',
    sourceTable: 'auth.users',
    sourceColumn: 'last_sign_in_at',
    relationships: 'auth.users.id joined to profiles.id when the auth/user mapping exists; otherwise unavailable because no login history table is present.',
    calculation: 'COUNT(*) WHERE last_sign_in_at IS NULL',
    timeWindow: 'Since inception',
    userAttribution: 'auth.users.id',
    companyAttribution: 'profiles.company_id via user_id',
    dataLimitations: 'The project currently does not provide a reliable app-level login event history table; this metric requires auth schema access and careful user mapping.',
    reliability: 'unavailable',
    available: false,
    reason: 'No login history table or reliable auth-user mapping was found in the existing schema without creating new infrastructure.',
  },
  {
    metric: 'Total Companies',
    purpose: 'Company records in the product.',
    sourceTable: 'companies',
    sourceColumn: 'id',
    relationships: 'companies.id is counted directly.',
    calculation: 'COUNT(DISTINCT companies.id)',
    timeWindow: 'Since inception',
    userAttribution: 'profiles.id via company relationships',
    companyAttribution: 'companies.id',
    dataLimitations: 'Counts organizations, not necessarily active paid customers.',
    reliability: 'high',
    available: true,
  },
  {
    metric: 'Users by Role',
    purpose: 'Count of users per role.',
    sourceTable: 'profiles',
    sourceColumn: 'role',
    relationships: 'Requires a role field on profiles or an org membership table; this cannot be assumed without schema verification.',
    calculation: 'COUNT(*) GROUP BY role',
    timeWindow: 'Since inception',
    userAttribution: 'profile.id',
    companyAttribution: 'profiles.company_id',
    dataLimitations: 'No role breakdown was confirmed in the current schema; this is unavailable until those fields are verified.',
    reliability: 'unavailable',
    available: false,
    reason: 'Role data is not confirmed in the current schema and must be verified before a reliable breakdown can be built.',
  },
  {
    metric: 'Users by Company',
    purpose: 'Distribution of users across organizations.',
    sourceTable: 'profiles',
    sourceColumn: 'company_id',
    relationships: 'Requires a verified company membership structure; if organisation_members exists, it may need a join.',
    calculation: 'COUNT(*) GROUP BY company_id',
    timeWindow: 'Since inception',
    userAttribution: 'profile.id',
    companyAttribution: 'profiles.company_id',
    dataLimitations: 'Current schema may support company linkage via profiles.company_id, but a definitive org-member hierarchy is not guaranteed.',
    reliability: 'unavailable',
    available: false,
    reason: 'The schema does not confirm a reliable user-to-company aggregate structure beyond profiles.company_id, so this remains a future metric.',
  },
  {
    metric: 'Companies by Subscription/Tier',
    purpose: 'Count of companies by subscription or pricing tier.',
    sourceTable: 'companies',
    sourceColumn: 'subscription_tier',
    relationships: 'Requires subscription fields on companies or a related pricing table.',
    calculation: 'COUNT(*) GROUP BY subscription tier',
    timeWindow: 'Since inception',
    userAttribution: 'profiles.id via company relationship',
    companyAttribution: 'companies.id',
    dataLimitations: 'No subscription or tier field was identified in the current schema; this is unavailable without a verified database field.',
    reliability: 'unavailable',
    available: false,
    reason: 'No confirmed subscription/tier column exists in the inspected schema.',
  },
  {
    metric: 'Jobs',
    purpose: 'Count of jobs in the system.',
    sourceTable: 'jobs',
    sourceColumn: 'id',
    relationships: 'jobs.id counted directly; user/company attribution through jobs.created_by and jobs.company_id.',
    calculation: 'COUNT(DISTINCT jobs.id)',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'jobs.created_by',
    companyAttribution: 'jobs.company_id',
    dataLimitations: 'Counts all job rows and does not guarantee active or approved status unless filters are added later.',
    reliability: 'high',
    available: true,
  },
  {
    metric: 'Applications',
    purpose: 'Count of application records.',
    sourceTable: 'applications',
    sourceColumn: 'id',
    relationships: 'applications.id counted directly; company attribution depends on jobs.company_id when available.',
    calculation: 'COUNT(DISTINCT applications.id)',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'jobs.created_by or downstream attribution when available',
    companyAttribution: 'jobs.company_id via job_id',
    dataLimitations: 'User attribution is only reliable when the downstream job/company joins are intact; otherwise attribution varies.',
    reliability: 'medium',
    available: true,
  },
  {
    metric: 'Import Batches',
    purpose: 'Count of import batch records.',
    sourceTable: 'import_batches',
    sourceColumn: 'id',
    relationships: 'import_batches.id is counted directly; attribution may use created_by or user_id when present.',
    calculation: 'COUNT(DISTINCT import_batches.id)',
    timeWindow: 'Since inception',
    userAttribution: 'import_batches.created_by or import_batches.user_id',
    companyAttribution: 'import_batches.company_id',
    dataLimitations: 'This is a count of batch records, not necessarily successful candidate imports or unique candidates.',
    reliability: 'medium',
    available: false,
    reason: 'Currently hardcoded to zero in overview.ts; no database query is performed. Planned for future implementation.',
  },
  {
    metric: 'Resume Imports',
    purpose: 'Count of uploaded resume import records.',
    sourceTable: 'resume_imports',
    sourceColumn: 'id',
    relationships: 'resume_imports.id counted directly; user/company attribution from user_id and company_id when present.',
    calculation: 'COUNT(DISTINCT resume_imports.id)',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'resume_imports.user_id',
    companyAttribution: 'resume_imports.company_id',
    dataLimitations: 'Counts import rows, not necessarily parse success or unique candidate records.',
    reliability: 'medium',
    available: true,
  },
  {
    metric: 'AI Agents',
    purpose: 'Count of agent records in the product.',
    sourceTable: 'ai_agents',
    sourceColumn: 'id',
    relationships: 'ai_agents.id counted directly; user/company attribution through created_by/company_id where these fields exist.',
    calculation: 'COUNT(DISTINCT ai_agents.id)',
    timeWindow: 'Since inception',
    userAttribution: 'ai_agents.created_by',
    companyAttribution: 'ai_agents.company_id',
    dataLimitations: 'This is a record count only; operational metrics such as failures or processing time are not available without an event table.',
    reliability: 'medium',
    available: true,
  },
  {
    metric: 'Interviews',
    purpose: 'Count of interview records.',
    sourceTable: 'interviews',
    sourceColumn: 'id',
    relationships: 'interviews.id counted directly; attribution may come from created_by and interviewer_id.',
    calculation: 'COUNT(DISTINCT interviews.id)',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'interviews.created_by / interviews.interviewer_id',
    companyAttribution: 'jobs.company_id via job_id',
    dataLimitations: 'Creator and interviewer attribution is only reliable as long as those columns are populated and the join path is valid.',
    reliability: 'medium',
    available: true,
  },
  {
    metric: 'Calls',
    purpose: 'Count of screening call records.',
    sourceTable: 'screening_calls',
    sourceColumn: 'id',
    relationships: 'screening_calls.id counted directly; attribution is inferred via related interview/campaign contexts.',
    calculation: 'COUNT(DISTINCT screening_calls.id)',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'not guaranteed without deeper join verification',
    companyAttribution: 'campaign-related company linkage when the schema supports it',
    dataLimitations: 'Call attribution is not consistently available across all rows because the schema does not guarantee which user or company contexts are stored.',
    reliability: 'medium',
    available: true,
  },
  {
    metric: 'Test Call Runs',
    purpose: 'Count of agent or QA call executions used for testing.',
    sourceTable: 'test_call_runs',
    sourceColumn: 'id',
    relationships: 'Requires a verified table shape and any created_by/user_id mapping.',
    calculation: 'COUNT(DISTINCT test_call_runs.id)',
    timeWindow: 'Since inception',
    userAttribution: 'test_call_runs.created_by or test_call_runs.user_id',
    companyAttribution: 'when available via company_id, otherwise unavailable',
    dataLimitations: 'The table may exist but requires verification before usage; it is not assumed to be present in this project.',
    reliability: 'unavailable',
    available: false,
    reason: 'No verified table or schema evidence for test_call_runs was found in the inspected workspace.',
  },
  {
    metric: 'Application Notes',
    purpose: 'Count of note records attached to applications.',
    sourceTable: 'application_notes',
    sourceColumn: 'id',
    relationships: 'Requires a verified table definition and application->note relationship.',
    calculation: 'COUNT(DISTINCT application_notes.id)',
    timeWindow: 'Since inception',
    userAttribution: 'application_notes.user_id',
    companyAttribution: 'when upstream application/company mapping is valid',
    dataLimitations: 'No confirmed schema for this table was identified, so it cannot be included as a reliable metric yet.',
    reliability: 'unavailable',
    available: false,
    reason: 'The application_notes table was not confirmed in the inspected project schema.',
  },
  {
    metric: 'System Health: Resume Processing',
    purpose: 'Attempts, successes, failures, and success rate for resume processing tasks.',
    sourceTable: 'resume_imports',
    sourceColumn: 'status',
    relationships: 'Depends on a persisted status or workflow outcome field; if absent, this metric is unavailable.',
    calculation: 'COUNT(*) by status / attempts vs success/failure ratio',
    timeWindow: 'Today / Yesterday / Last 7 / Last 30 / Since inception',
    userAttribution: 'user_id or created_by when available',
    companyAttribution: 'company_id when available',
    dataLimitations: 'No reliable success/failure event stream was found in the inspected schema; this is a future operational metric.',
    reliability: 'unavailable',
    available: false,
    reason: 'The existing database does not appear to persist failed attempts or status histories required for success-rate analytics.',
  },
];